version: '3'

services:
  symfony:
    image: symfony-personal
    container_name: symfony-personal
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/app
    ports:
      - '5003:8081'