version: '3'

services:
  symfony:
    image: symfony-personal
    container_name: symfony-personal
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/app
    ports:
      - '5003:8081'


  pgsql:
    container_name: symfony-database
    image: postgres:9.5
    environment:
      - POSTGRES_DB=symfony_test1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"