controllers:
    resource: ../src/Controller/
    type: attribute

#index:
##    path: /
#    path: /hello/{name}
#    controller: 'App\Controller\DefaultController::index'

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
