<?php

namespace App\Controller\Admin;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Security;

class BaseController extends AbstractController
{


    public function __construct(Security $security)
    {
//        var_dump($security->);exit();
//        var_dump($this->isGranted('ROLE_USER'));exit();

//        $this->access_control($security);
    }

    public function access_control($security){
//        $security->isGranted('ROLE_USER');

    }
//    public function setContainer(ContainerInterface $container): ?ContainerInterface
//    {
//        var_dump($this->); exit();
//        return parent::setContainer($container); // TODO: Change the autogenerated stub
//    }

}
